#####################################################################
#   Extruder
#####################################################################

##  Connected to MOTOR_6 / Heater - HE0 / Thermistor - T0
[extruder]
step_pin: EBBCan:PD0
dir_pin: EBBCan:PD1
enable_pin: !EBBCan:PD2

##  Update value below when you perform extruder calibration
##  If you ask for 100mm of filament, but in reality it is 98mm:
##  rotation_distance = <previous_rotation_distance> * <actual_extrude_distance> / 100
##  22.6789511 is a good starting point for Bondtech 5mm drive gears.
rotation_distance: 22.22537208  # MDF measured 2023-03-28

gear_ratio: 50:10               # BMG Gear Ratio / Stealthburner CW2 = 50:10
microsteps: 32
full_steps_per_rotation: 200    # 200 for 1.8 degree, 400 for 0.9 degree
nozzle_diameter: 0.600          # Error if requested extruded amount exceeds capacity of 0.6 nozzle
filament_diameter: 1.75
instantaneous_corner_velocity: 1.5
max_extrude_cross_section: 0.8

heater_pin: EBBCan:PB13

## Check what thermistor type you have. See
## https://www.klipper3d.org/Config_Reference.html#common-thermistors
## for common thermistor types.
## Use "Generic 3950" for NTC 100k 3950 thermistors
sensor_type: Generic 3950
sensor_pin: EBBCan:PA3
min_temp: 0
max_temp: 260
max_power: 1.0
min_extrude_temp: 170

pressure_advance: 0.05
#pressure_advance_smooth_time: 0.040

[tmc2240 extruder]
cs_pin: EBBCan:PA15
spi_software_sclk_pin: EBBCan:PB10
spi_software_mosi_pin: EBBCan:PB11
spi_software_miso_pin: EBBCan:PB2
interpolate: False
run_current: 0.65
rref: 12000
stealthchop_threshold: 999999

# Recommendations by AndrewMcgr and Esoterical

driver_IHOLDDELAY: 8
driver_IRUNDELAY: 2
driver_TBL: 3
driver_TOFF: 4
driver_HEND: 3
driver_HSTRT: 4
driver_TPFD: 0
driver_PWM_AUTOSCALE: True
driver_PWM_AUTOGRAD: True
driver_PWM_GRAD: 7 # was 12
driver_PWM_OFS: 19 # was 40
driver_PWM_REG: 15
driver_PWM_LIM: 12
driver_SGT: 55  # Stallguard threshold; may need adjustment
driver_SEMIN: 2
driver_SEMAX: 8

diag0_pin: EBBCan:PB3

[gcode_macro configure_extruder]
gcode:
  # Enable accurate stall current measurement
  SET_TMC_FIELD STEPPER=extruder FIELD=pwm_meas_sd_enable VALUE=1
  SET_TMC_FIELD STEPPER=extruder FIELD=sg4_filt_en VALUE=1
  # Allow the motor to freewheel when not in use, means it runs cooler
  SET_TMC_FIELD STEPPER=extruder FIELD=freewheel VALUE=1
  # Set the StealthChop stall detection threshold (may not be completely necessary)
  SET_TMC_FIELD STEPPER=extruder FIELD=SG4_THRS VALUE=10
  # Set the hold current to zero, and completely switch off the motor when it is not in use
  SET_TMC_FIELD STEPPER=extruder FIELD=IHOLD VALUE=0
  # Set the max expected velocity to a value such that we are unlikely to switch to fullstepping except during a very fast retraction or prime
  SET_TMC_FIELD STEPPER=extruder FIELD=THIGH VELOCITY=50
  # Use CoolStep, but we need a certain step frequency for it to work
  SET_TMC_FIELD STEPPER=extruder FIELD=TCOOLTHRS VALUE=4000
  # But do switch to PWM autotuning when at high flow
  SET_TMC_FIELD STEPPER=extruder FIELD=TPWMTHRS VELOCITY=1
  # Set the temperature prewarning to something reasonable. Cosmetic, Klipper does nothing with this
  SET_TMC_FIELD STEPPER=extruder FIELD=OVERTEMPPREWARNING_VTH VALUE=2885 # 7.7 * 100 C + 2038
  # The following is absolutely critical: set the overvoltage snubber to a sensible voltage.
  # This should be set to about 0.8 V above your power supply's idle voltage.
  # Your PSU voltage can be read from the TMC 2240 by issuing a GCODE command:
  # DUMP_TMC stepper=extruder register=ADC_VSUPPLY_AIN
  # The voltage is the value of adc_vsupply multiplied by 0.009732
  # It is also possible to use adc_vsupply + 82 here, which works out to be the same.
#  {% set v = (24.7/0.009732)|int %}
  {% set v = (2482+82) %}
  SET_TMC_FIELD STEPPER=extruder FIELD=OVERVOLTAGE_VTH VALUE={ v }
