#####################################################################
#   Extruder
#####################################################################

##  Connected to MOTOR_6 / Heater - HE0 / Thermistor - T0
[extruder]
step_pin: MOT6_STEP
dir_pin: MOT6_DIR
enable_pin: !MOT6_EN

##  Update value below when you perform extruder calibration
##  If you ask for 100mm of filament, but in reality it is 98mm:
##  rotation_distance = <previous_rotation_distance> * <actual_extrude_distance> / 100
##  22.6789511 is a good starting point
#rotation_distance: 22.6789511  # Bondtech 5mm Drive Gears
rotation_distance: 22.22537208  # MDF measured 2023-03-28

gear_ratio: 50:10               # BMG Gear Ratio / Stealthburner CW2 = 50:10
microsteps: 32
full_steps_per_rotation: 200    # 200 for 1.8 degree, 400 for 0.9 degree
nozzle_diameter: 0.400
filament_diameter: 1.75
heater_pin: HE0

## Check what thermistor type you have. See
## https://www.klipper3d.org/Config_Reference.html#common-thermistors
## for common thermistor types.
## Use "Generic 3950" for NTC 100k 3950 thermistors
sensor_type: Generic 3950
sensor_pin: T0
min_temp: 10
max_temp: 270
max_power: 1.0
min_extrude_temp: 170

#control = pid
#pid_kp = 26.213
#pid_ki = 1.304
#pid_kd = 131.721

pressure_advance: 0.05
#pressure_advance_smooth_time: 0.040

[tmc2209 extruder]
uart_pin: MOT6_CS
interpolate: false
run_current: 0.5
sense_resistor: 0.110
stealthchop_threshold: 0

