#####################################################################
#   Fan Control
#####################################################################

##  Print Cooling Fan - FAN0
[fan]
#pin: FAN0
pin: EBBCan:PA1
kick_start_time: 0.5
off_below: 0.10        # Values below 10% will turn it off.

##  Hotend Fan - FAN1
[heater_fan hotend_fan]
#pin: FAN1
pin: EBBCan:PA0
max_power: 1.0
kick_start_time: 0.5
heater: extruder
heater_temp: 50.0      # Fan turns off below this temperature.
##  If you are experiencing back flow, you can reduce fan_speed
#fan_speed: 1.0

##  Controller fan rear - FAN2
[controller_fan controller_fan_rear]
pin: FAN2
kick_start_time: 0.5
heater: heater_bed
fan_speed: 0.33
idle_timeout: 300
idle_speed: 0.25

##  Controller fan front - FAN4
[controller_fan controller_fan_front]
pin: FAN3
kick_start_time: 0.5
heater: heater_bed
fan_speed: 0.33
idle_timeout: 300
idle_speed: 0.25

##  Exhaust fan - FAN4
#[heater_fan exhaust_fan]
#pin: FAN4
#max_power: 1.0
#shutdown_speed: 0.0
#kick_start_time: 5.0
#heater: heater_bed
#heater_temp: 60
#fan_speed: 1.0