##  Inductive Probe
##  This probe is not used for Z height, only Quad Gantry Leveling
[probe]
pin: ESTOP7

x_offset: 0
y_offset: 25.0
z_offset: 0

speed: 8
samples: 3
samples_result: median
sample_retract_dist: 3.0
samples_tolerance: 0.006
samples_tolerance_retries: 3
