##  Use QUAD_GANTRY_LEVEL to level a gantry.
##  Min & Max gantry corners - measure from nozzle at MIN (0,0) and 
##  MAX (250, 250), (300,300), or (350,350) depending on your printer size
##  to respective belt positions

[quad_gantry_level]
gantry_corners:
   -60,-10
   360,370
points:
   50,25
   50,225
   250,225
   250,25

speed: 250               # How fast to move between probe locations
horizontal_move_z: 10    # How high to move Z before each probe
retries: 5
retry_tolerance: 0.01
max_adjust: 12
