[gcode_macro PRIME_NOZZLE]
gcode:
    SAVE_GCODE_STATE NAME=PRIME_NOZZLE_STATE
    STATUS_CLEANING
    M117 Priming nozzle...
    G90                 ; Absolute coordinates.
    M83                 ; Relative extruder mode.
    G92 E0
    ; Move to start of line.
    G1 Z10 F900
    G1 Y3 X3 F18000
    G1 Z0.2 F900
    ; Print the line.
    G91                ; Relative coordinates.
    G1 X100 E25 F1000  ; Extrude filament 25mm (how much it retracted in PRINT_END).
    G1 Y-2 F1000
    G1 X-60 E9 F1000    ; Print second part of the line.
    G1 E-0.5 F3000      ; Retract to avoid stringing.
    G1 X0.5 E0 F1000    ; Wipe back to break string.
    G1 X-5.5 E0 F1000   ; Wipe forward to break string.
    STATUS_READY
    RESTORE_GCODE_STATE NAME=PRIME_NOZZLE_STATE

###
## PRINT_START
###
[gcode_macro PRINT_START]
gcode:
    # Parameters from slicer
    {% set bedtemp = params.BED | int %}
    {% set hotendtemp = params.EXTRUDER | int %}
    {% set chambertemp = params.CHAMBER | default(0) | int %}

    M107                       ; Part fan off

    STATUS_HEATING
    M117 Heating bed and nozzle...
    M104 S150                  ; Set nozzle to heat to 150C - soften filament, but no oozing.
    M190 S{bedtemp}            ; Wait for bed to reach target temperature.

    G32                        ; home X/Y/Z

    SETUP_KAMP_MESHING DISPLAY_PARAMETERS=1 LED_ENABLE=1 FUZZ_ENABLE=1
    BED_MESH_CLEAR
    M117 Adaptive bed meshing...
    BED_MESH_CALIBRATE

    G90                        ; absolute positioning

    STATUS_HEATING
    M117 Heating nozzle...
    M109 S{hotendtemp}  ; Wait for nozzle to get to target temperature.

    PRIME_NOZZLE

    G90                 ; Absolute coordinates.
    M83                 ; Relative extruder mode.
    G92 E0

    STATUS_PRINTING
    M117 Printing...

[gcode_macro PRINT_END]
gcode:    # safe anti-stringing move coords
    {% set th = printer.toolhead %}
    {% set x_safe = th.position.x + 20 * (1 if th.axis_maximum.x - th.position.x > 20 else -1) %}
    {% set y_safe = th.position.y + 20 * (1 if th.axis_maximum.y - th.position.y > 20 else -1) %}
    {% set z_safe = [th.position.z + 2, th.axis_maximum.z]|min %}
    
    SAVE_GCODE_STATE NAME=STATE_PRINT_END
    
    M400                           ; wait for buffer to clear
    G92 E0                         ; zero the extruder
    G1 E-5.0 F1800                 ; retract filament
    
    G90                                      ; absolute positioning
    G0 X{x_safe} Y{y_safe} Z{z_safe} F20000  ; move nozzle to remove stringing
    G1 E-20.0 F3600                  ; retract filament another 20mm (completely out of hot zone)

    TURN_OFF_HEATERS
    
    M107                                     ; turn off fan
    G0 X{th.axis_maximum.x//2} Y{th.axis_maximum.y - 2} F3600  ; park nozzle at rear

    M117 Done

    BED_MESH_CLEAR
    RESTORE_GCODE_STATE NAME=STATE_PRINT_END
